#!/usr/bin/env python
# -*- coding: latin-1 -*-

import Process

if Process.verifyCommands("lame")==False:
	sys.exit()

Process.ProcessFiles(
	"lame -h --decode $FILE$ $NAME$.wav", # comando a ejecutar
	"mp3", # tipo de archivos
	True, # leer directorios?
	False, # procesar directorio como un archivo
	"") # mensaje final
