#!/usr/bin/env python
# -*- coding: latin-1 -*-

import Process

if Process.verifyCommands("lame|oggdec%vorbis-tools")==False:
	sys.exit()

Process.ProcessFiles(
	"oggdec $FILE$", # comando a ejecutar
	"ogg", # tipo de archivos
	True, # leer directorios?
	False, # procesar directorio como un archivo
	"") # mensaje final

Process.ProcessFiles(
	"lame -h -m j $NAME$.wav $NAME$.mp3", # comando a ejecutar
	"ogg", # tipo de archivos
	True, # leer directorios?
	False, # procesar directorio como un archivo
	"") # mensaje final

Process.ProcessFiles(
	"rm $NAME$.wav", # comando a ejecutar
	"ogg", # tipo de archivos
	True, # leer directorios?
	False, # procesar directorio como un archivo
	"") # mensaje final
