#!/usr/bin/env python
# -*- coding: latin-1 -*-

import Process

if Process.verifyCommands("oggdec%vorbis-tools")==False:
	sys.exit()

Process.ProcessFiles(
	"oggdec $FILE$", # comando a ejecutar
	"ogg", # tipo de archivos
	True, # leer directorios?
	False, # procesar directorio como un archivo
	"") # mensaje final
