#!/usr/bin/env python
# -*- coding: latin-1 -*-

import Process

import gtk
import os
import sys
import string

def ClickAceptar(widget):

	time = str(int(spinMin.get_value())) + "." + str(int(spinSeg.get_value()))

	Process.ProcessFiles(
		"mp3splt -t " + time + " $FILE$", # comando a ejecutar
		"mp3", # tipo de archivos
		False, # leer directorios?
		False, # procesar directorio como un archivo
		"Procedura terminata") # mensaje final
	gtk.main_quit()

def ClickCancelar(widget):
	gtk.main_quit()

# PROGRAMA

if Process.verifyCommands("mp3splt")==False:
	sys.exit()

w = gtk.Window(gtk.WINDOW_TOPLEVEL)
w.set_title("Suddividere Mp3")
w.set_border_width(20)

w.connect("destroy", gtk.main_quit) 

# tabla

tableMin = gtk.Table(2, 1, False)
tableMin.set_border_width(10)

tableMin.set_row_spacings(8)
tableMin.set_col_spacings(8)


lTime = gtk.Label("Spezzoni di tempo [min:sec]")

tableMin.attach(lTime, 0, 1, 0, 1)

box = gtk.HBox(True, 4)

adjMin = gtk.Adjustment(1.0, 0.0, 60.0, 1.0, 5.0, 0.0)
spinMin = gtk.SpinButton(adjMin, 0, 0)
adjMin.set_value(0)
box.pack_start(spinMin, False, False, 0)

adjSeg = gtk.Adjustment(1.0, 0.0, 60.0, 1.0, 5.0, 0.0)
spinSeg = gtk.SpinButton(adjSeg, 0, 0)
adjSeg.set_value(0)
box.pack_start(spinSeg, False, False, 0)

tableMin.attach(box, 1, 2, 0, 1)


# botones

aligBotones = gtk.Alignment(1.0, 0.0)
boxBotones = gtk.HBox(True, 4)

bAceptar = gtk.Button("Accettare", gtk.STOCK_OK)

bAceptar.connect("clicked", ClickAceptar)

boxBotones.pack_start(bAceptar, False, False, 0)

bCancelar = gtk.Button("Annullare", gtk.STOCK_CANCEL)

bCancelar.connect("clicked", ClickCancelar)

boxBotones.pack_start(bCancelar, False, False, 0)

aligBotones.add(boxBotones)

tableMin.attach(aligBotones, 1, 2, 2, 3)

w.add(tableMin)
w.show_all()
gtk.main()
