#!/usr/bin/env python
# -*- coding: latin-1 -*-

import Process

if Process.verifyCommands("convert%ImageMagick")==False:
	sys.exit()

Process.ProcessFiles(
	"convert -flip $FILE$ $FILE$", # comando a ejecutar
	"jpg|png", # tipo de archivos
	False, # leer directorios?
	False, # procesar directorio como un archivo
	"") # mensaje final
