#!/bin/bash

##########################################################################
# Send To
##########################################################################
#                                                                        #
# Created by Mattia Galati (Adaron)                                      #
# first improvement and translation by Christopher Bratusek (Chrispy)    #
#                                                                        #
##########################################################################
# Language Settings ---------------------------------------------------- #
destination='Destinazione'
title_destination='Invia i files a:'

copy='Copia in corso'
title_copy='Attendere...'

success='File copiati correttamente'
title_success='Successo'

errors='Si sono verificati degli errori'
title_errors='Errore'

no_writable='La destinazione può non esistere o non essere scrivibile'
title_no_writable='Errore'
# End of language settings ----------------------------------------------#
##########################################################################

devices=`ls -m /media/`
vv=${devices//cdrom?, /}
vd=${vv//cdrom, /}
options=${vd//, / FALSE /media/}
destinazione=`zenity --list --title "$title_destination" --text "$destination" --radiolist --column " " --column "Device" FALSE /media/$options`

if [[ "$destinazione" = "" ]]; then
    exit
fi

if [[ -w $destinazione ]]; then
	cp -R $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS $destinazione | zenity --progress --pulsate --auto-close --title="$title_copy" --text="$copy"
	if (( $? == 0 )); then
		zenity --info --text="$success" --title "$title_success";
	else	zenity --info --text="$errors" --title "$title_errors";
	fi
else	zenity --info --text="$no_writable" --title "$title_no_writable";
fi
